export const DEGREE_LEVEL = {
  SUPER_SUPER_LOW: 0,
  SUPER_LOW: 1,
  LOW: 2,
  MIDDLE: 3,
  HEIGHT: 4,
  SUPER_HEIGHT: 5,
  SUPER_SUPER_HEIGHT: 6,
  HYPER_HEIGHT: 7,
  HYPER_HYPER_HEIGHT: 8,
  ULTIMATE_HEIGHT: 9,
} as const;
